# nodjs buidl pipeline with Dockerfile

trigger:
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - src/*
    - .ci/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: build
  jobs:
  - job: build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - task: Docker@2
      displayName: 'Build an image'
      inputs:
        repository: 'mydockerhubid/mydockerhubrepo'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Push an image'
      inputs:
        command: 'push'
        repository: 'mydockerhubid/mydockerhubrepo'
        tags: |
          $(Build.BuildId)
          latest