trigger:
  - pipeline: build-push
    stage: build
    condition: succeeded()
    branches:
      include:
      - master
      - develop
    paths:
      include:
      - src/*
      - .ci/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Bash@3
  displayName: 'Change tag in file'
  inputs:
    targetType: 'inline'
    script: |
      # get the last 6 characters of the commit id
      commitId=$(Build.SourceVersion)
      commitId=${commitId: -6}
      # change the tag in the file
      sed -i "s/commitId/$commitId/g" src/index.html
      # show the file
      cat src/index.html