apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: hello-world-frontend
  name: hello-world-frontend
  namespace: hello-world
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: hello-world-frontend
  type: ClusterIP
